- name: Install git and docker dependencies
  become: yes
  ansible.builtin.package:
    name:
      - git
      - ca-certificates
      - curl
      - gnupg
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest

- name: Add the Docker apt repository
  become: yes
  block:
    - name: Download the Docker key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/trusted.gpg.d/docker.asc

    - name: Add the Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present

- name: Update apt and install docker-ce
  become: yes
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest

- name: Install Docker Module for Python
  pip:
    name:
      - docker
      - docker-compose

- name: Adding user to docker group
  become: yes
  user:
    name: "{{ hostvars['bastion'].ansible_user_id }}"
    groups: docker
    append: yes

- name: Reset ssh connection to allow user changes to affect ansible user
  ansible.builtin.meta:
    reset_connection

- name: Clone caronte repository
  ansible.builtin.git:
    repo: https://github.com/eciavatta/caronte.git
    dest: ./caronte

- name: Docker compose up
  community.docker.docker_compose:
    project_src: caronte
    files: docker-compose.yml
    recreate: "always"

- name: Pause for 10 seconds to ensure container start
  ansible.builtin.pause:
    seconds: 10

- name: Caronte setup
  ansible.builtin.uri:
    url: "http://{{ hostvars['bastion'].ansible_host }}:3333/setup"
    status_code: [202, 404, 200]
    method: post
    body_format: json
    body:
      config:
        server_address: "{{ hostvars['vuln'].ansible_host }}"
        flag_regex: "{{ flags_regex }}"
        auth_required: true
      accounts:
        admin: "{{ pwd }}" 
